//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineEXAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSet
    {
        public int Question_ID { get; set; }
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public string correctOption { get; set; }
        public int MainCateogryID { get; set; }
        public int Subject_id { get; set; }
        public int Topic_id { get; set; }
    
        public virtual maincateogry maincateogry { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
